kegweb/kegweb/main/urls.py
__author__ = 'tim'

from django.conf.urls import patterns, url

urlpatterns = patterns('kegweb.main.views',
                       url(r'^face/(?P<userid>\d+)/delete/(?P<faceid>\d+)/$', 'deleteface', name='deleteface'),
                       url(r'^face/(?P<userid>\d+)/$', 'face', name='face'),
                       )

kegweb/kegweb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^admin/',include(admin.site.urls)),
                       (r'^kegweb/', include('kegweb.main.urls')),
                       (r'^$', RedirectView.as_view(url='/kegweb/')),  # Just for ease of use.
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kegweb/kegweb/main/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from kegweb import settings

__author__ = 'tim'

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
# * Rearrange models' order
# * Make sure each model has one field with primary_key=True
# * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models


class Event(models.Model):
    name = models.CharField(max_length=45)
    date = models.DateField()
    description = models.TextField()

    class Meta:
        db_table = 'event'


class Facedata(models.Model):
    user = models.ForeignKey(User)
    photo = models.ImageField(upload_to="facedb/", null=False, blank=False)
    added = models.DateTimeField(auto_now_add=True, blank=False, null=False)

    class Meta:
        db_table = 'facedata'


class KegUser(models.Model):
    user = models.OneToOneField(User)
    photo = models.ImageField(upload_to="profile/", null=True, blank=True)

    class Meta:
        db_table = 'keguser'


class Pour(models.Model):
    eventid = models.ForeignKey(Event, db_column='eventid', blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    volume = models.FloatField()
    pourphoto = models.ImageField(upload_to="pourimg/", blank=False, null=False)
    facebooked = models.BooleanField()
    time = models.DateTimeField()

    class Meta:
        db_table = 'pour'


class Userevent(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    eventid = models.ForeignKey(Event, db_column='eventid', blank=True, null=True)
    firstpour = models.DateTimeField(blank=True, null=True)
    lastpour = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'userevent'

kegweb/kegweb/main/forms.py
__author__ = 'tim'

from django import forms


class FacedataForm(forms.Form):
    face = forms.FileField(

    )
    leftEyeX = forms.IntegerField(min_value=0, widget=forms.TextInput(attrs={'class':'xyinput left'}))
    rightEyeX = forms.IntegerField(min_value=0, widget=forms.TextInput(attrs={'class':'xyinput right'}))
    leftEyeY = forms.IntegerField(min_value=0, widget=forms.TextInput(attrs={'class':'xyinput left'}))
    rightEyeY = forms.IntegerField(min_value=0, widget=forms.TextInput(attrs={'class':'xyinput right'}))

kegweb/kegweb/main/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from kegweb.main.models import Facedata
from kegweb.main.forms import FacedataForm
from facelib import crop_face


def face(request, userid=1):
    # Handle file upload
    if request.method == 'POST':
        form = FacedataForm(request.POST, request.FILES)
        if form.is_valid():
            # extract form data
            lx = int(request.POST['leftEyeX'])
            ly = int(request.POST['leftEyeY'])
            rx = int(request.POST['rightEyeX'])
            ry = int(request.POST['rightEyeY'])
            # crop the face
            face = crop_face.crop_form_image(request.FILES['face'], eye_left=(lx, ly), eye_right=(rx, ry))


            # send pic for processing

            # save facedata
            newdoc = Facedata(photo=face, user_id=userid)
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('kegweb.main.views.face', kwargs={'userid': userid}))
    else:
        form = FacedataForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Facedata.objects.all().filter(user_id=userid)

    # Render list page with the documents and the form
    return render_to_response(
        'kegweb/faces.html',
        {'documents': documents, 'form': form, 'userid': userid},
        context_instance=RequestContext(request)
    )


def deleteface(request, faceid=0, userid=0):
    Facedata.objects.get(id=faceid).delete()
    return HttpResponse("yep")


def index():
    User.objects.get()
    return "derp"

kegweb/kegweb/main/templates/kegweb/faces.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Minimal Django File Upload Example</title>
    <link type="text/css" rel="stylesheet" href="/static/main/css/style.css"/>
</head>

<body>
<!-- used for eye positioning -->
<img class="cross" id="crossLeft" src="/static/main/images/crossred.png">
<img class="cross" id="crossRight" src="/static/main/images/crossblue.png">
<!-- List of uploaded documents -->
<div class="facelist">
    {% if documents %}
        {% for document in documents %}
            <span class="tenthumb">
            <a class="imgdel" href="{%  url "deleteface" faceid=document.id userid=userid %}">[x]</a>
            <img class="tenthumb" src="{{ document.photo.url }}"/>
            </span>
        {% endfor %}
    {% else %}
        <p>No documents.</p>
    {% endif %}
</div>


<!-- Upload form. Note enctype attribute! -->
<form action="{% url "face" userid=userid  %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="leftpane">
        <p>{{ form.non_field_errors }}</p>

        <p>{{ form.face.label_tag }} {{ form.face.help_text }}</p>

        <p>
            <button type="button" onclick="setLeftEye();return false;">Left Eye:</button>
            {{ form.leftEyeX }},{{ form.leftEyeY }}</p>
        <p>
            <button type="button" onclick="setRightEye();return false;">Right Eye:</button>
            {{ form.rightEyeX }},{{ form.rightEyeY }}</p>
        <p><input type="submit" value="Upload"/></p>
    </div>
    <div class="mainpane">
        <p>
            {{ form.face.errors }}
            {{ form.face }}
        </p>
        <img id="preview" src="#" alt="Preview of uploaded image"/>
    </div>

</form>
<script type="text/javascript" src="/static/main/js/jquery-2.1.0.min.js"></script>

<script type="text/javascript">
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    function setLeftEye() {
        var $preview = $("#preview");
        $preview.css("cursor", "crosshair");
        $preview.one('click',function (event) {
            event.preventDefault(); //because browsers be crazy
            var lx = 0;
            var ly = 0;
            if (event.offsetTop) {
                lx = event.offsetLeft;
                ly = event.offsetTop;
            } else {
                lx = event.pageX-$preview[0].offsetLeft;
                ly = event.pageY-$preview[0].offsetTop;
            }
            $("#id_leftEyeX").val(lx);
            $("#id_leftEyeY").val(ly);
            $("#crossLeft").css({
                left:event.pageX-50,
                top:event.pageY-50
            });
            console.log(lx+" "+ly);
            $preview.css("cursor", "default");
        });

        return true;
    }

    function setRightEye() {
        var $preview = $("#preview");
        $preview.css("cursor", "crosshair");
        $preview.one('click',function (event) {
            event.preventDefault(); //because browsers be crazy
            var rx = 0;
            var ry = 0;
            if (event.offsetTop) {
                rx = event.offsetLeft;
                ry = event.offsetTop;
            } else {
                rx = event.pageX-$preview[0].offsetLeft;
                ry = event.pageY-$preview[0].offsetTop;
            }
            $("#id_rightEyeX").val(rx);
            $("#id_rightEyeY").val(ry);
            $("#crossRight").css({
                left:event.pageX-50,
                top:event.pageY-50//these are hackish, should get the crosshair size to determine this
            });
            console.log(rx+" "+ry);
            $preview.css("cursor", "default");

        });
    }



    $("#id_face").change(function () {
        readURL(this);
    });

    $(".imgdel").on('click',function (event){
        var el = this
        $.get(this.href,function(){
            console.log("deleting parent");
            $(el).parent().remove();
        });
        event.preventDefault();
        return false;
    });


</script>

</body>

</html> 

kegweb/kegweb/main/templates/kegweb/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

kegweb/kegweb/main/templates/kegweb/profile.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>